version: "3"
services:
  ewallet:
    build: .
    depends_on:
      db:
        condition: service_started
      migration:
        condition: service_completed_successfully
    ports:
      - 8081:8080
    networks:
      - default
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ewallet?sslmode=disable

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ewallet

  migration:
    build: migrations
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./migrations:/migrations:ro
    networks:
      - default
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ewallet?sslmode=disable
    command: sh -c "sleep 10 && migrate -path /migrations -database $${DATABASE_URL} up"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8082:8080
    volumes:
      - ./api:/api:ro
    environment:
      SWAGGER_JSON: /api/openapi.yaml

volumes:
  db:

networks:
  default:
