name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21.0,<1.22.0'
    - uses: pre-commit/action@v3.0.1
